-- MySQL Script generated by MySQL Workbench
-- Ter 29 Abr 2014 03:00:46 BRT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sga` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sga` ;

-- -----------------------------------------------------
-- Table `sga`.`fazendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`fazendas` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `proprietario` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `saldo` DECIMAL(10,2) NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `inscricaoestatual` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `atividades` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`sexos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`sexos` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `pessoa_count` INT NULL,
  `user_count` INT NULL,
  `user_disable` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`pessoas` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `sexo_id` INT(10) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NULL COMMENT 'status de acesso ao sistema',
  `contabanco` VARCHAR(255) NOT NULL,
  `nascimento` DATE NOT NULL,
  `carteiratrabalho` VARCHAR(255) NOT NULL,
  `anexo` VARCHAR(255) NULL,
  `anexo_dir` VARCHAR(255) NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(11) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `cidade` VARCHAR(255) NOT NULL,
  `rua` VARCHAR(255) NULL,
  `bairro` VARCHAR(255) NULL,
  `cep` VARCHAR(255) NULL,
  `telefone` VARCHAR(255) NOT NULL,
  `datecontratado` DATE NOT NULL,
  `premiacoes` TEXT NULL,
  `parent_id` INT(10) NULL COMMENT 'user subordinados',
  `lft` INT(10) NULL,
  `rght` INT(10) NULL,
  `foto` VARCHAR(45) NULL,
  `foto_dir` VARCHAR(45) NULL,
  `updated` DATETIME NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_users_sexo1_idx` (`sexo_id` ASC),
  CONSTRAINT `fk_users_sexo1`
    FOREIGN KEY (`sexo_id`)
    REFERENCES `sga`.`sexos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`retiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`retiros` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `fazenda_id` INT(10) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cod_ordenha` INT NULL,
  `descricao` TEXT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_retiro_fazendas1` (`fazenda_id` ASC),
  CONSTRAINT `fk_retiro_fazendas1`
    FOREIGN KEY (`fazenda_id`)
    REFERENCES `sga`.`fazendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`pastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`pastos` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `retiro_id` INT(10) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NULL COMMENT 'Tipo de Pasto pode ser:' /* comment truncated */ /*	Pastagens Nativas
	Pastagens Cultivadas
	Pastagens Adubadas

*/,
  `datainclusao` DATETIME NULL,
  `area` DECIMAL(8,2) NOT NULL,
  `topografia` VARCHAR(15) NULL COMMENT 'Topografia pode ser:' /* comment truncated */ /*	Plano
	Ondulado
	Inclinado
*/,
  `tipoaguado` TINYINT(1) NOT NULL COMMENT 'Tipo aguada pode ser ' /* comment truncated */ /*	Natural
	Artificial*/,
  `bovino_count` INT NULL DEFAULT 0,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pastos_retiro1` (`retiro_id` ASC),
  CONSTRAINT `fk_pastos_retiro1`
    FOREIGN KEY (`retiro_id`)
    REFERENCES `sga`.`retiros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`acos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`acos` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `parent_id` INT(10) NULL DEFAULT NULL,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  `foreign_key` INT(10) NULL DEFAULT NULL,
  `alias` VARCHAR(255) NULL DEFAULT NULL,
  `lft` INT(10) NULL DEFAULT NULL,
  `rght` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `sga`.`aros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`aros` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `parent_id` INT(10) NULL DEFAULT NULL,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  `foreign_key` INT(10) NULL DEFAULT NULL,
  `alias` VARCHAR(255) NULL DEFAULT NULL,
  `lft` INT(10) NULL DEFAULT NULL,
  `rght` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `sga`.`aros_acos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`aros_acos` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `aro_id` INT(10) NULL,
  `aco_id` INT(10) NULL,
  `_create` VARCHAR(2) NOT NULL DEFAULT '0',
  `_read` VARCHAR(2) NOT NULL DEFAULT '0',
  `_update` VARCHAR(2) NOT NULL DEFAULT '0',
  `_delete` VARCHAR(2) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ARO_ACO_KEY` (`aro_id` ASC, `aco_id` ASC),
  INDEX `fk_aros_acos_acos_1_idx` (`aco_id` ASC),
  INDEX `fk_aros_acos_aros_1_idx` (`aro_id` ASC),
  CONSTRAINT `fk_aros_acos_acos_1`
    FOREIGN KEY (`aco_id`)
    REFERENCES `sga`.`acos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aros_acos_aros_1`
    FOREIGN KEY (`aro_id`)
    REFERENCES `sga`.`aros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `sga`.`sexobovinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`sexobovinos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `count` VARCHAR(45) NULL,
  `bovino_count` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`categoriabs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`categoriabs` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NOT NULL,
  `bovino_count` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Categoria pode ser:	' /* comment truncated */ /*	Lactente
	Em crescimento
	Novilha
	Vaca*/;


-- -----------------------------------------------------
-- Table `sga`.`pelagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`pelagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `bovino_count` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`bovinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`bovinos` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `pai` INT(10) NULL,
  `mae` INT(10) NULL,
  `pasto_id` INT(10) NOT NULL,
  `categoriab_id` INT(10) NOT NULL COMMENT 'categoria atual bovino',
  `sexobovino_id` INT NOT NULL,
  `pelagen_id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `nbrinco` VARCHAR(45) NULL,
  `nascimento` DATETIME NULL,
  `desaleitamento` TINYINT(1) NULL,
  `aptas` TINYINT(1) NULL DEFAULT 1 COMMENT '1 - Aptas' /* comment truncated */ /*0 - Inaptas*/,
  `preco` DECIMAL(10,2) NULL,
  `cria` INT NULL DEFAULT 0 COMMENT 'total de cria',
  `cascosnormais` INT NULL DEFAULT 4,
  `descricao` TEXT NULL,
  `idcompra` INT NULL COMMENT 'caso animal seja comprado id da compra',
  `idvenda` INT NULL COMMENT 'caso animal seja vendido id da venda',
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bovinos_pastos1_idx` (`pasto_id` ASC),
  INDEX `fk_bovinos_sexobovinos1_idx` (`sexobovino_id` ASC),
  INDEX `fk_bovinos_categoriabs1_idx` (`categoriab_id` ASC),
  INDEX `fk_bovinos_bovinos1_idx` (`pai` ASC),
  INDEX `fk_bovinos_bovinos2_idx` (`mae` ASC),
  INDEX `fk_bovinos_pelagem1_idx` (`pelagen_id` ASC),
  CONSTRAINT `fk_bovinos_pastos1`
    FOREIGN KEY (`pasto_id`)
    REFERENCES `sga`.`pastos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bovinos_sexobovinos1`
    FOREIGN KEY (`sexobovino_id`)
    REFERENCES `sga`.`sexobovinos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bovinos_categoriabs1`
    FOREIGN KEY (`categoriab_id`)
    REFERENCES `sga`.`categoriabs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bovinos_bovinos1`
    FOREIGN KEY (`pai`)
    REFERENCES `sga`.`bovinos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bovinos_bovinos2`
    FOREIGN KEY (`mae`)
    REFERENCES `sga`.`bovinos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bovinos_pelagem1`
    FOREIGN KEY (`pelagen_id`)
    REFERENCES `sga`.`pelagens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`racas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`racas` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `origem` VARCHAR(45) NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`bovinos_racas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`bovinos_racas` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `bovino_id` INT(10) NOT NULL,
  `raca_id` INT(10) NOT NULL,
  `percentual` DECIMAL(4,2) NOT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_animais_has_raca_raca1` (`raca_id` ASC),
  INDEX `fk_animais_has_raca_animais1` (`bovino_id` ASC),
  CONSTRAINT `fk_animais_has_raca_animais1`
    FOREIGN KEY (`bovino_id`)
    REFERENCES `sga`.`bovinos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animais_has_raca_raca1`
    FOREIGN KEY (`raca_id`)
    REFERENCES `sga`.`racas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`categoriaseventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`categoriaseventos` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB
COMMENT = 'Comunicação de cobri�' /* comment truncated */ /*ão

Comunicação de nascimento (parto)
Autorização de transferencia
ComTipo de ocorrencia secagens
Estorno secagem*/;


-- -----------------------------------------------------
-- Table `sga`.`semems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`semems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `pai` INT NULL,
  `mae` INT NULL,
  `data` DATETIME NOT NULL,
  `origem` TEXT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`ics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`ics` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `bovino_id` INT(10) NULL COMMENT 'Pai',
  `semem_id` INT NULL,
  `tipo` VARCHAR(255) NOT NULL COMMENT 'IA (Inseminação Artificia' /* comment truncated */ /*)
MC (Monta Controlada)
MN (Monta Campo)*/,
  `status` VARCHAR(255) NOT NULL COMMENT '0 - ICS' /* comment truncated */ /*1 - Gestante
2 - parto
3 - Abordo*/,
  `data` DATETIME NOT NULL COMMENT 'IA (Inseminação Artificia' /* comment truncated */ /*)
MC (Monta Controlada)
MN (Monta Campo)*/,
  `dataparto` DATETIME NULL,
  `descricao` TEXT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ics_bovinos1_idx` (`bovino_id` ASC),
  INDEX `fk_ics_semems1_idx` (`semem_id` ASC),
  CONSTRAINT `fk_ics_bovinos1`
    FOREIGN KEY (`bovino_id`)
    REFERENCES `sga`.`bovinos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ics_semems1`
    FOREIGN KEY (`semem_id`)
    REFERENCES `sga`.`semems` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'IA (Inseminação Artificia' /* comment truncated */ /*)
MC (Monta Controlada)
MN (Monta Campo)*/;


-- -----------------------------------------------------
-- Table `sga`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`groups` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `user_count` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`users` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  `sexo_id` INT(10) NOT NULL,
  `group_id` INT(10) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `foto_dir` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_users_sexos1_idx` (`sexo_id` ASC),
  INDEX `fk_users_groups1_idx` (`group_id` ASC),
  CONSTRAINT `fk_users_sexos1`
    FOREIGN KEY (`sexo_id`)
    REFERENCES `sga`.`sexos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `sga`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Usuários';


-- -----------------------------------------------------
-- Table `sga`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`eventos` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) NOT NULL,
  `bovino_id` INT(10) NOT NULL,
  `status` INT(1) NULL COMMENT 'status da ocorrencia' /* comment truncated */ /*1 - aberto
2 - fechado
3 - em andamento*/,
  `categoriasevento_id` INT(10) NOT NULL COMMENT 'categoria da ocorrencia',
  `nome` VARCHAR(255) NULL,
  `datainicial` DATETIME NULL,
  `alerta` TINYINT(1) NULL COMMENT 'notifica relacionados',
  `datafinal` DATETIME NULL,
  `datamax` DATETIME NULL COMMENT 'data maximo para termino da ocorrencia',
  `secagens` TINYINT(1) NULL COMMENT '60 dias para regeneração dos tecidos secretores do leite',
  `iniciosecagem` DATE NULL,
  `altura` VARCHAR(45) NULL,
  `pesagem` VARCHAR(45) NULL,
  `desaleitamento` DATETIME NULL,
  `cascosnormais` INT NULL,
  `aptas` TINYINT(1) NULL,
  `leitepesagens` DECIMAL(10,2) NULL,
  `escore` INT NULL COMMENT 'nota para avaliar peso anima entre 1 a 9',
  `ic_id` INT(10) NULL,
  `descricao` TEXT NULL,
  `diagnostico` TEXT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ocorrencias_tipoocorrencias1_idx` (`categoriasevento_id` ASC),
  UNIQUE INDEX `created_UNIQUE` (`datainicial` ASC),
  INDEX `fk_ocorrencias_ics1_idx` (`ic_id` ASC),
  INDEX `fk_ocorrencias_bovinos1_idx` (`bovino_id` ASC),
  INDEX `fk_ocorrencias_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_ocorrencias_tipoocorrencias1`
    FOREIGN KEY (`categoriasevento_id`)
    REFERENCES `sga`.`categoriaseventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocorrencias_ics1`
    FOREIGN KEY (`ic_id`)
    REFERENCES `sga`.`ics` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ocorrencias_bovinos1`
    FOREIGN KEY (`bovino_id`)
    REFERENCES `sga`.`bovinos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ocorrencias_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sga`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`clientes` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `cpf` CHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NULL,
  `email` VARCHAR(255) NOT NULL,
  `contato` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `municipio` VARCHAR(45) NULL,
  `cep` VARCHAR(8) NULL,
  `estato` CHAR(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`fornecedores` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `municipio` VARCHAR(45) NULL,
  `cep` VARCHAR(8) NULL,
  `estato` CHAR(2) NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NULL,
  `email` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `inscricaoestatual` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`accounts` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `fazenda_id` INT(10) NOT NULL,
  `banco` VARCHAR(45) NOT NULL,
  `agencia` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contas_fazendas1_idx` (`fazenda_id` ASC),
  CONSTRAINT `fk_contas_fazendas1`
    FOREIGN KEY (`fazenda_id`)
    REFERENCES `sga`.`fazendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`doencas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`doencas` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`fabricantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`fabricantes` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `contato` VARCHAR(45) NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Marca, Fabricantes';


-- -----------------------------------------------------
-- Table `sga`.`categoriaps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`categoriaps` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL COMMENT 'ordenha,',
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fornecedore_id` INT(10) NOT NULL,
  `nome` VARCHAR(225) NULL,
  `quantidade` INT NULL,
  `valor` DECIMAL(5,2) NULL,
  `emissao` DATETIME NULL,
  `pago` TINYINT(1) NULL DEFAULT 0 COMMENT '0 - Debito' /* comment truncated */ /*1 - Pago*/,
  `descricao` TEXT NULL,
  `data` DATE NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compras_fornecedores1_idx` (`fornecedore_id` ASC),
  CONSTRAINT `fk_compras_fornecedores1`
    FOREIGN KEY (`fornecedore_id`)
    REFERENCES `sga`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`patrimonios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`patrimonios` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `fabricante_id` INT(10) NULL,
  `fazenda_id` INT(10) NULL,
  `categoriap_id` INT(10) NULL,
  `compra_id` INT NULL,
  `unidade` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `comprado` TINYINT(1) NOT NULL DEFAULT 1,
  `depreciacao` DECIMAL(5,2) NULL COMMENT 'perca em porcentagem',
  `descricao` TEXT NULL,
  `created` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_fablicantes1` (`fabricante_id` ASC),
  INDEX `fk_patrimonio_fazendas1_idx` (`fazenda_id` ASC),
  INDEX `fk_patrimonios_categoria_patrimonio1_idx` (`categoriap_id` ASC),
  INDEX `fk_patrimonios_compras1_idx` (`compra_id` ASC),
  CONSTRAINT `fk_produtos_fablicantes1`
    FOREIGN KEY (`fabricante_id`)
    REFERENCES `sga`.`fabricantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patrimonio_fazendas1`
    FOREIGN KEY (`fazenda_id`)
    REFERENCES `sga`.`fazendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patrimonios_categoria_patrimonio1`
    FOREIGN KEY (`categoriap_id`)
    REFERENCES `sga`.`categoriaps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patrimonios_compras1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `sga`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 's bens permanentes';


-- -----------------------------------------------------
-- Table `sga`.`receituarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`receituarios` (
  `idreceituario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`idreceituario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`groups_categoriaseventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`groups_categoriaseventos` (
  `id` INT(20) NOT NULL,
  `group_id` INT(10) NOT NULL,
  `categoriasevento_id` INT(10) NOT NULL,
  `alerta` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_rules_has_tipoocorrencias_tipoocorrencias1_idx` (`categoriasevento_id` ASC),
  INDEX `fk_roles_categorias_groups1_idx` (`group_id` ASC),
  CONSTRAINT `fk_rules_has_tipoocorrencias_tipoocorrencias1`
    FOREIGN KEY (`categoriasevento_id`)
    REFERENCES `sga`.`categoriaseventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_categorias_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `sga`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`cotacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`cotacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contrato` VARCHAR(255) NOT NULL,
  `ultimo` DECIMAL(10,2) NOT NULL,
  `variacao` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`clientes_fazendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`clientes_fazendas` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `cliente_id` INT(10) NOT NULL,
  `fazenda_id` INT(10) NOT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  INDEX `fk_clientes_has_fazendas_fazendas1_idx` (`fazenda_id` ASC),
  INDEX `fk_clientes_has_fazendas_clientes1_idx` (`cliente_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_clientes_has_fazendas_clientes1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `sga`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_has_fazendas_fazendas1`
    FOREIGN KEY (`fazenda_id`)
    REFERENCES `sga`.`fazendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`fazendas_pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`fazendas_pessoas` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `fazenda_id` INT(10) NOT NULL,
  `pessoa_id` INT(10) NOT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  INDEX `fk_fazendas_users_users1_idx` (`pessoa_id` ASC),
  INDEX `fk_fazendas_users_fazendas1_idx` (`fazenda_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_fazendas_users_fazendas1`
    FOREIGN KEY (`fazenda_id`)
    REFERENCES `sga`.`fazendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fazendas_users_users1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `sga`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`cargos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `habilidade` VARCHAR(255) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `diasalario` INT NOT NULL COMMENT 'dia do mês',
  `pontos` INT NULL,
  `descricao` TEXT NOT NULL,
  `updated` DATETIME NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`pessoas_cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`pessoas_cargos` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT(10) NOT NULL,
  `cargo_id` INT(10) NOT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  INDEX `fk_users_cargos_cargos1_idx` (`cargo_id` ASC),
  INDEX `fk_users_cargos_users1_idx` (`pessoa_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_cargos_users1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `sga`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_cargos_cargos1`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `sga`.`cargos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`fazendas_fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`fazendas_fornecedores` (
  `int` INT(10) NOT NULL AUTO_INCREMENT,
  `fazenda_id` INT(10) NOT NULL,
  `fornecedore_id` INT(10) NOT NULL,
  PRIMARY KEY (`int`),
  INDEX `fk_fazendas_fornecedores_fornecedores1_idx` (`fornecedore_id` ASC),
  INDEX `fk_fazendas_fornecedores_fazendas1_idx` (`fazenda_id` ASC),
  CONSTRAINT `fk_fazendas_fornecedores_fazendas1`
    FOREIGN KEY (`fazenda_id`)
    REFERENCES `sga`.`fazendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fazendas_fornecedores_fornecedores1`
    FOREIGN KEY (`fornecedore_id`)
    REFERENCES `sga`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`medicamentos` (
  `id` INT(10) NOT NULL,
  `fazenda_id` INT(10) NOT NULL,
  `fabricante_id` INT(10) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `categoria` VARCHAR(255) NULL,
  `notafiscal` INT NULL,
  `unidade` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `comprado` TINYINT(1) NULL,
  `descricao` TEXT NULL,
  `created` DATETIME NULL,
  `dose` DOUBLE NULL COMMENT 'campos: criar conponente add',
  `validade` TIMESTAMP NULL COMMENT 'campos: criar conponente add',
  `prescricao` TEXT NULL COMMENT 'campos: criar conponente add',
  PRIMARY KEY (`id`),
  INDEX `fk_almoxarifados_fabricantes1_idx` (`fabricante_id` ASC),
  INDEX `fk_almoxarifados_fazendas1_idx` (`fazenda_id` ASC),
  CONSTRAINT `fk_almoxarifados_fabricantes1`
    FOREIGN KEY (`fabricante_id`)
    REFERENCES `sga`.`fabricantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_almoxarifados_fazendas1`
    FOREIGN KEY (`fazenda_id`)
    REFERENCES `sga`.`fazendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`atalhos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`atalhos` (
  `id` INT NOT NULL,
  `user_id` INT(10) NOT NULL,
  `title` CHAR(255) NOT NULL,
  `controller` VARCHAR(45) NOT NULL,
  `action` VARCHAR(45) NULL,
  `prefixes` VARCHAR(45) NULL,
  `plugin` VARCHAR(45) NULL,
  `class` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atalhos_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_atalhos_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sga`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`eventos_doencas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`eventos_doencas` (
  `id` INT NOT NULL,
  `evento_id` INT(10) NOT NULL,
  `doenca_id` INT(10) NOT NULL,
  `diagnostico` TEXT NULL,
  `created` VARCHAR(45) NULL,
  `updated` VARCHAR(45) NULL,
  INDEX `fk_eventos_has_doencas_doencas1_idx` (`doenca_id` ASC),
  INDEX `fk_eventos_has_doencas_eventos1_idx` (`evento_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_eventos_has_doencas_eventos1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `sga`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_has_doencas_doencas1`
    FOREIGN KEY (`doenca_id`)
    REFERENCES `sga`.`doencas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'diagnosticos de doenças';


-- -----------------------------------------------------
-- Table `sga`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `fabricante_id` INT(10) NULL,
  `descricao` TEXT NULL,
  `valor` DECIMAL(10,2) NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_fabricantes1_idx` (`fabricante_id` ASC),
  CONSTRAINT `fk_produtos_fabricantes1`
    FOREIGN KEY (`fabricante_id`)
    REFERENCES `sga`.`fabricantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Ingrediente para consumo animal' /* comment truncated */ /*Medicamento
Anima/Embrião
Sêmen
Outros*/;


-- -----------------------------------------------------
-- Table `sga`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produto_id` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  `cliente_id` INT(10) NULL,
  `patrimonio_id` INT(10) NULL,
  `quantidade` VARCHAR(45) NULL,
  `valor` DECIMAL(10,2) NULL COMMENT '0 - Debito' /* comment truncated */ /*1 - Pago*/,
  `pago` TINYINT(1) NULL DEFAULT 0 COMMENT 'Patrimonio',
  `emissao` DATETIME NULL,
  `descricao` VARCHAR(45) NULL,
  `data` DATE NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vendas_clientes1_idx` (`cliente_id` ASC),
  INDEX `fk_vendas_patrimonios1_idx` (`patrimonio_id` ASC),
  INDEX `fk_vendas_produtos1_idx` (`produto_id` ASC),
  CONSTRAINT `fk_vendas_clientes1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `sga`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_patrimonios1`
    FOREIGN KEY (`patrimonio_id`)
    REFERENCES `sga`.`patrimonios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_produtos1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `sga`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`meteorologicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`meteorologicos` (
  `id` INT NOT NULL,
  `data` DATETIME NULL,
  `umidademin` INT NULL,
  `umidademax` INT NULL,
  `chuma` INT NULL COMMENT 'mm',
  `temperaturamin` INT NULL,
  `temperaturamax` INT NULL,
  `observacoes` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`ordenhas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`ordenhas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `local` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`leitepesagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`leitepesagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bovino_id` INT(10) NOT NULL,
  `ordenha_id` INT NOT NULL,
  `peso` DECIMAL(5,2) NOT NULL,
  `data` DATETIME NOT NULL,
  `escore` INT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_leitepesagens_ordenhas1_idx` (`ordenha_id` ASC),
  INDEX `fk_leitepesagens_bovinos1_idx` (`bovino_id` ASC),
  CONSTRAINT `fk_leitepesagens_ordenhas1`
    FOREIGN KEY (`ordenha_id`)
    REFERENCES `sga`.`ordenhas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leitepesagens_bovinos1`
    FOREIGN KEY (`bovino_id`)
    REFERENCES `sga`.`bovinos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`pesagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`pesagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bovino_id` INT(10) NOT NULL,
  `peso` VARCHAR(45) NULL,
  `data` VARCHAR(45) NULL,
  `pasto_id` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL COMMENT 'ex: fim desmama, peso ao nascer, peso as 12 meses',
  PRIMARY KEY (`id`),
  INDEX `fk_pesagens_bovinos1_idx` (`bovino_id` ASC),
  CONSTRAINT `fk_pesagens_bovinos1`
    FOREIGN KEY (`bovino_id`)
    REFERENCES `sga`.`bovinos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`movbovinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`movbovinos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bovino_id` INT(10) NOT NULL,
  `pasto_id` INT(10) NOT NULL,
  `pastoanterior` VARCHAR(45) NULL,
  `data` DATETIME NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movbovinos_bovinos1_idx` (`bovino_id` ASC),
  INDEX `fk_movbovinos_pastos1_idx` (`pasto_id` ASC),
  CONSTRAINT `fk_movbovinos_bovinos1`
    FOREIGN KEY (`bovino_id`)
    REFERENCES `sga`.`bovinos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movbovinos_pastos1`
    FOREIGN KEY (`pasto_id`)
    REFERENCES `sga`.`pastos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`custos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`custos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item` VARCHAR(255) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'controle de custos anuais e mensais';


-- -----------------------------------------------------
-- Table `sga`.`fornecimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`fornecimentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `retiro_id` INT(10) NOT NULL,
  `data` DATETIME NOT NULL,
  `quantidade` DECIMAL(5,2) NOT NULL,
  `preco` DECIMAL(5,2) NOT NULL,
  `observacoes` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fornecimentos_retiros1_idx` (`retiro_id` ASC),
  CONSTRAINT `fk_fornecimentos_retiros1`
    FOREIGN KEY (`retiro_id`)
    REFERENCES `sga`.`retiros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'fornecimento de leite';


-- -----------------------------------------------------
-- Table `sga`.`calendarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`calendarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fazenda_id` INT(10) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `inicio` DATETIME NOT NULL,
  `termino` DATETIME NULL,
  `observacoes` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_calendarios_fazendas1_idx` (`fazenda_id` ASC),
  CONSTRAINT `fk_calendarios_fazendas1`
    FOREIGN KEY (`fazenda_id`)
    REFERENCES `sga`.`fazendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`medicamentos_bovinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`medicamentos_bovinos` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `medicamento_id` INT(10) NOT NULL,
  `bovino_id` INT(10) NOT NULL,
  `observacoes` VARCHAR(455) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medicamentos_has_bovinos_bovinos1_idx` (`bovino_id` ASC),
  INDEX `fk_medicamentos_has_bovinos_medicamentos1_idx` (`medicamento_id` ASC),
  CONSTRAINT `fk_medicamentos_has_bovinos_medicamentos1`
    FOREIGN KEY (`medicamento_id`)
    REFERENCES `sga`.`medicamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentos_has_bovinos_bovinos1`
    FOREIGN KEY (`bovino_id`)
    REFERENCES `sga`.`bovinos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`centralcustos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`centralcustos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mes` DATE NOT NULL,
  `quantidade` VARCHAR(50) NULL,
  `custofixo` DECIMAL(10,2) NULL,
  `outrosvalores` DECIMAL(10,2) NULL,
  `custovariavel` DECIMAL(10,2) NULL,
  `descricao` TEXT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `compras_id` INT NOT NULL,
  `vendas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_centralcustos_compras1_idx` (`compras_id` ASC),
  INDEX `fk_centralcustos_vendas1_idx` (`vendas_id` ASC),
  CONSTRAINT `fk_centralcustos_compras1`
    FOREIGN KEY (`compras_id`)
    REFERENCES `sga`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_centralcustos_vendas1`
    FOREIGN KEY (`vendas_id`)
    REFERENCES `sga`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'central de custo pode ter varios custos';


-- -----------------------------------------------------
-- Table `sga`.`centralcustos_custos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`centralcustos_custos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `centralcusto_id` INT NOT NULL,
  `custo_id` INT NOT NULL,
  `valor` DECIMAL(10,2) NULL COMMENT 'valor atual de custos',
  INDEX `fk_central_has_custos_custos1_idx` (`custo_id` ASC),
  INDEX `fk_central_has_custos_central1_idx` (`centralcusto_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_central_has_custos_central1`
    FOREIGN KEY (`centralcusto_id`)
    REFERENCES `sga`.`centralcustos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_central_has_custos_custos1`
    FOREIGN KEY (`custo_id`)
    REFERENCES `sga`.`custos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
